name: Default template
labels: "bug"
description: It is recommended to use this template if you don't want to type out everything. (It's also user friendly) You can create a blank one if you want.
body:
  - type: textarea
    id: describe-the-issue
    attributes:
      label: What is the issue?
      description: Please describe the issue thoroughly. Include any errors and pictures/videos of the issues where possible.
    validations:
      required: true
  - type: checkboxes
    id: which-repo
    attributes:
      optional: false
      label: Which repo is it coming from?
      options:
        - label: The main repo (the root)
        - label: The blog repo
  - type: textarea
    id: comments
    attributes:
      label: Any comments?
      description: This is an optional field. You are not required to fill this out.